apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ryanj-8-poi-map-app-dev
  annotations:
    argocd/app-name: ryanj-8-poi-map-app-dev
    backstage.io/kubernetes-id: ryanj-8-poi-map-app-dev
    backstage.io/kubernetes-namespace: ryanj-8
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=ryanj-8-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23DevLab/ryanj-8
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://devspaces.apps.summit23.0x74.p1.openshiftapps.com/#https://github.com/Summit23DevLab/ryanj-8?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:blues-man"
  system: workshop-system-ryanj-8
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-ryanj-8
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:blues-man"
